### ISSUE TITLE
Can you provide a quick start example?

### ISSUE THREAD

**Issue by LukeWood** [google-research/python-graphs#10]
Super cool project!  Love the idea and think it has a lot of potential.

it would be awesome to have an examples/ directory containing some sample usages - maybe even just plotting the graphs with networkX and matplotlib.

**Comment by aaeagal** [comment]
I agree!

**Comment by dbieber** [comment]
To start you off check out the existing examples directory:
https://github.com/google-research/python-graphs/tree/main/python_graphs/examples

**Comment by LukeWood** [comment]
any reason to have examples nested under the library itself?

**Comment by dbieber** [comment]
Nope. Moving them to the top level will be an improvement 👍

**Comment by dbieber** [comment]
I've moved the examples directory to the top level.
