### ISSUE TITLE
How do we solve the error when installing python-graphs?

### ISSUE THREAD

**Issue by fraolBatole** [google-research/python-graphs#12]
Hello,

I encountered an error "fatal error: 'graphviz/cgraph.h' file not found" when trying to install python_graphs. How do I solve this issue, please? Thanks.

**Comment by dbieber** [comment]
Ah, you'll have to install graphviz to get past that error.
On mac this is e.g. "brew install graphviz"

**Comment by dbieber** [comment]
On ubuntu it would be "apt-get install libgraphviz-dev"
